import json
import logging
from typing import Any, Dict

import google.generativeai as genai

from src.core.config import Config


class TheJudge:
    """
    Implements the Self-Evaluation Module (Constitutional AI).
    Evaluates the quality of the Agent's output against the User's input.
    """

    def __init__(self):
        self.config = Config.load()
        genai.configure(api_key=self.config.GOOGLE_API_KEY)
        self.logger = logging.getLogger("ZenithJudge")

        # Initialize the Judge Model
        self.model = genai.GenerativeModel(
            model_name=self.config.MODEL_NAME,
            system_instruction=self._get_system_prompt(),
        )

    def _get_system_prompt(self) -> str:
        return """
        ATUE COMO: O Juiz Supremo (The Judge). Uma IA de Auditoria Constitucional Especializada em Qualidade de Software e Prompt Engineering.
        
        SUA MISSÃO: Classificar objetivamente a resposta de uma IA para um determinado input de usuário.
        
         ### RUBRICA DE AVALIAÇÃO (0-100 PONTOS)
        
        1. **Fidelidade à Intenção (0-35 pontos):**
           - A resposta atende EXATAMENTE ao que foi pedido?
           - Ignorou alguma restrição explícita?
        
        2. **Robustez e Segurança (0-25 pontos):**
           - A resposta é segura? Contém alucinações?
           - O código (se houver) é seguro e não malicioso?
        
        3. **Clareza e Didatismo (0-20 pontos):**
           - A formatação está impecável (Markdown)? 
           - A linguagem é adequada ao nível de complexidade?
        
        4. **Eficiência (0-20 pontos):**
           - Foi direto ao ponto ou "encheu linguiça"?
           - A solução é elegante?
        
        ### OUTPUT SCHEMA (JSON OBRIGATÓRIO)
        Retorne APENAS um JSON válido. Sem Markdown de código (```json).
        
        {
          "score": int, // Soma total (0-100)
          "feedback": "string", // Crítica construtiva e direta de 1 frase.
          "needs_refinement": boolean // True se score < 80
        }
        """

    def evaluate(self, user_input: str, model_output: str) -> Dict[str, Any]:
        """
        Evaluates the interaction.
        Args:
            user_input: The user's original request.
            model_output: The text generated by the Zenith Agent.
        Returns:
            Dict containing score and feedback.
        """
        self.logger.info("👨‍⚖️ The Judge is in session. Auditing response...")

        prompt = f"""
        [INPUT DO USUÁRIO]
        {user_input}
        
        [RESPOSTA DA IA]
        {model_output}
        
        [TAREFA]
        Avalie a [RESPOSTA DA IA] com base na [INPUT DO USUÁRIO] usando a Rubrica.
        Gere o JSON de saída.
        """

        try:
            response = self.model.generate_content(
                prompt,
                generation_config={
                    "temperature": 0.0,
                    "response_mime_type": "application/json",
                },
            )

            raw_text = response.text.strip()

            # Clean possible markdown formatting constraints
            if raw_text.startswith("```json"):
                raw_text = raw_text[7:]
            if raw_text.startswith("```"):
                raw_text = raw_text[3:]
            if raw_text.endswith("```"):
                raw_text = raw_text[:-3]

            result = json.loads(raw_text)

            self.logger.info(
                f"Verdict: Score {result.get('score')} | Refinement: {result.get('needs_refinement')}"
            )
            return result

        except Exception as e:
            self.logger.error(f"Judge Execution Failed: {e}. Defaulting to safe score.")
            return self._get_fallback_evaluation()

    def _get_fallback_evaluation(self) -> Dict[str, Any]:
        """
        Fallback for when the Judge fails (API error, parsing error).
        """
        return {
            "score": 85,
            "feedback": "Avaliação indisponível (Erro no Juiz). Qualidade assumida como Padrão.",
            "needs_refinement": False,
        }
